import {
  google,
  googleFull,
  ibm,
  meta,
  salesforce,
  intuit,
  hubspot,
  illinois,
  duke,
  michigan,
  stanford,
  penn,
  aws,
  amil,
  atlassian,
  caseWestern,
  deepLearningAi,
  imperialCollege,
  facebook,
  michiganFull,
  deepLearningAiFull,
  stanfordCollege,
  courseraLearning,
  nyu,
  unt,
  uOfIllinois,
  macquarie,
} from "../Icon/PartnerLogo";
import pythonCard from "../../Assets/pythonCard.png";
import leaderCard from "../../Assets/leaderCard.png";
import meaningCard from "../../Assets/meaningCard.png";
import excelCard from "../../Assets/excelCard.png";
import mlCard from "../../Assets/mlCard.png";
import securityCard from "../../Assets/securityCard.png";
import businessCard from "../../Assets/businessCard.png";
import adminCard from "../../Assets/adminCard.png";
import dataScienceCard from "../../Assets/dataScienceCard.png";

const tabs = [
  {
    id: 1,
    category: "All",
  },
  {
    id: 2,
    category: "Data science",
  },
  {
    id: 3,
    category: "Business",
  },
  {
    id: 4,
    category: "Computer science",
  },
  {
    id: 5,
    category: "Marketing",
  },
  {
    id: 6,
    category: "Technology",
  },
  {
    id: 7,
    category: "Language learning",
  },
  {
    id: 8,
    category: "Personal development",
  },
  {
    id: 9,
    category: "Information technology",
  },
];

const cards = [
  { id: 1, 
    intro: true,
    category: "All",
    product: "skill",
    title: "Learn a new skill in under 2 hours", 
    subTitle: "In a Guided Project, a subject matter expert guides you through key steps in a video that plays in a split-screen with your work area.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 2, 
    intro: false,
    category: "All",
    product: "skill",
    title: "Introduction to Relational Database and SQL", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [courseraLearning],
    org: ["Coursera Project Network"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 3, 
    intro: false,
    category: "All",
    product: "skill",
    title: "Introduction to Bash Shell Scripting", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [courseraLearning],
    org: ["Coursera Project Network"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 4, 
    intro: false,
    category: "All",
    product: "skill",
    title: "Business Analysis & Process Management", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [courseraLearning],
    org: ["Coursera Project Network"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },

  { id: 5, 
    intro: true,
    category: "All",
    product: "course",
    title: "Explore a new topic in your industry with a course", 
    subTitle: "Choose from over 5,200 courses, developed by leading universities and companies around the world.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 6, 
    intro: false,
    category: "All",
    product: "course",
    title: "Programming for Everybody (Getting Started with Python)", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [michigan],
    org: ["University of Michigan"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 7, 
    intro: false,
    category: "All",
    product: "course",
    title: "Leading Teams: Developing as a Leader", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [uOfIllinois],
    org: ["University of Illinois at Urbana-Champaign"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 8, 
    intro: false,
    category: "All",
    product: "course",
    title: "Finding Purpose and Meaning In Life: Living for What Matters Most", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [michigan],
    org: ["University of Michigan"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },

  { id: 9, 
    intro: true,
    category: "All",
    product: "specialization",
    title: "Gain expertise in an area with a Specialization ", 
    subTitle: "With a Specialization, you’ll master a skill by taking a series of courses and complete a hands-on project, and earn a certificate to share with employers and your professional network.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 10, 
    intro: false,
    category: "All",
    product: "specialization",
    title: "Excel Skills for Business", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [macquarie],
    org: ["Macquarie University"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 11, 
    intro: false,
    category: "All",
    product: "specialization",
    title: "Machine Learning", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [deepLearningAi, stanford],
    org: ["DeepLearningAI, Stanford University"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 12, 
    intro: false,
    category: "All",
    product: "specialization",
    title: "Introduction to Cyber Security", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [nyu],
    org: ["New York University"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Data Science, Deep Learning, Machine Learning, Big Data, Data Mining, Github, Python Programming, Jupyter notebooks, Rstudio, Methodology, Data Analysis, Pandas",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },

  { id: 13, 
    intro: true,
    category: "All",
    product: "degree",
    title: "Begin your path towards a degree", 
    subTitle: "Advance in your career / take the next step in your career with an affordable, 100% online degree from a top university. Test the waters with a MasterTrack, and earn university credit that you can stack into a degree program.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 10, 
    intro: false,
    category: "All",
    product: "degree",
    title: "Bachelor of Science in General Business", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [unt],
    org: ["University of North Texas"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Analysis, Business Analysis, Chart, Computational Logic, Computer Science",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 11, 
    intro: false,
    category: "All",
    product: "degree",
    title: "Master of Business Administration (iMBA)", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [uOfIllinois],
    org: ["University of Illinois at Urbana-Champaign"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Professional Certificate", "3+ Months"], 
    status: [],
    skills: "Accounting, Algorithms, Applied Machine Learning, Artificial Neural Network",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 12, 
    intro: false,
    category: "All",
    product: "degree",
    title: "Master of Applied Data Science", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg?auto=format%2Ccompress&dpr=2&w=150&h=150&fit=fill&bg=FFF&q=25", 
    org_img: [michigan],
    org: ["University of Michigan"], 
    rating: "4.6 (65,553)", 
    enrolled: "1.1m students", 
    categories: ["Degree", "1-3 years"], 
    status: [],
    skills: "Algorithms, BlockChain, Computer Networking, Computer Security",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
]


const skill = [
  { id: 1, 
    intro: true,
    category: "All",
    product: "skill",
    title: "Learn a new skill in under 2 hours", 
    subTitle: "In a Guided Project, a subject matter expert guides you through key steps in a video that plays in a split-screen with your work area.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 2, 
    intro: false,
    category: "All",
    product: "skill",
    title: "Introduction to Relational Database and SQL", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/ba/4f26a24daf4207ac94d4d1ec41fb15/SQL1_square.jpg?auto=format%2Ccompress&dpr=2&w=330&h=330&fit=fill&q=25", 
    org_img: [courseraLearning],
    org: ["Coursera Project Network"], 
    rating: "4.6 (326 reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Guided project", "2 hours"], 
    status: [],
    skills: "Data Science, Database (DBMS), Relational Database, MySQL, SQL",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 3, 
    intro: false,
    category: "All",
    product: "skill",
    title: "Introduction to Bash Shell Scripting", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/4e/05a0573df64b13bfbd05dc9bab31fb/project-1-.png?auto=format%2Ccompress&dpr=2&w=330&h=330&fit=fill&q=25", 
    org_img: [courseraLearning],
    org: ["Coursera Project Network"], 
    rating: "4.5 (113 reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Guided project", "2 hours"], 
    status: [],
    skills: "Scripting, Bash (Unix Shell), Linux, Unix",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 4, 
    intro: false,
    category: "All",
    product: "skill",
    title: "Business Analysis & Process Management", 
    subTitle: "",
    course_img: "https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera-course-photos/ab/db2b29824443a5a33b7c7e194f3b20/Logo.png?auto=format%2Ccompress&dpr=2&w=330&h=330&fit=fill&q=25", 
    org_img: [courseraLearning],
    org: ["Coursera Project Network"], 
    rating: "4.3 (184 reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Guided project", "2 hours"], 
    status: [],
    skills: "Scripting, Bash (Unix Shell), Linux, Unix",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
]

const course = [
  { id: 1, 
    intro: true,
    category: "All",
    product: "course",
    title: "Explore a new topic in your industry with a course", 
    subTitle: "Choose from over 5,200 courses, developed by leading universities and companies around the world.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 2, 
    intro: false,
    category: "All",
    product: "course",
    title: "Programming for Everybody (Getting Started with Python)", 
    subTitle: "",
    course_img: pythonCard, 
    org_img: [michigan],
    org: ["University of Michigan"], 
    rating: "4.6 (326 reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Course", "1-3 Months"], 
    status: [],
    skills: "Data Science, Database (DBMS), Relational Database, MySQL, SQL",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 3, 
    intro: false,
    category: "All",
    product: "course",
    title: "Leading Teams: Developing as a Leader", 
    subTitle: "",
    course_img: leaderCard, 
    org_img: [uOfIllinois],
    org: ["University of Illinois at Urbana-Champaign"], 
    rating: "4.8 (5.1k reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Course", "1-3 Months"], 
    status: [],
    skills: "Self-awareness, Ethical decision-making, Trust in relationships, Leadership",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 4, 
    intro: false,
    category: "All",
    product: "course",
    title: "Finding Purpose and Meaning In Life: Living for What Matters Most", 
    subTitle: "",
    course_img: meaningCard, 
    org_img: [michigan],
    org: ["University of Michigan"], 
    rating: "4.6 (1.8k reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Course", "1-4 Weeks"], 
    status: [],
    skills: "Resilience, Entrepreneurship, Business Psychology",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  }
]

const specialization = [
  { id: 1, 
    intro: true,
    category: "All",
    product: "specialization",
    title: "Gain expertise in an area with a Specialization ", 
    subTitle: "With a Specialization, you’ll master a skill by taking a series of courses and complete a hands-on project, and earn a certificate to share with employers and your professional network.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 2, 
    intro: false,
    category: "All",
    product: "specialization",
    title: "Excel Skills for Business", 
    subTitle: "",
    course_img: excelCard, 
    org_img: [macquarie],
    org: ["Macquarie University"], 
    rating: "4.9 (52.8k reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Specialization", "3-6 Months"], 
    status: [],
    skills: "Analysis, Business Analysis, Chart, Computational Logic, Computer Science",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 3, 
    intro: false,
    category: "All",
    product: "specialization",
    title: "Machine Learning", 
    subTitle: "",
    course_img: mlCard, 
    org_img: [deepLearningAi, stanford],
    org: ["DeepLearningAI, Stanford University"], 
    rating: "4.9 (1.1k reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Specialization", "1-3 Months"], 
    status: [],
    skills: "Accounting, Algorithms, Applied Machine Learning, Artificial Neural Network",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 4, 
    intro: false,
    category: "All",
    product: "specialization",
    title: "Introduction to Cyber Security", 
    subTitle: "",
    course_img: securityCard, 
    org_img: [nyu],
    org: ["New York University"], 
    rating: "4.7 (2.7k reviews)", 
    enrolled: "1.1m students", 
    categories: ["Beginner", "Specialization", "3-6 Months"], 
    status: [],
    skills: "Algorithms, BlockChain, Computer Networking, Computer Security",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  }
]

const degree = [
  { id: 1, 
    intro: true,
    category: "All",
    product: "degree",
    title: "Begin your path towards a degree", 
    subTitle: "Advance in your career / take the next step in your career with an affordable, 100% online degree from a top university. Test the waters with a MasterTrack, and earn university credit that you can stack into a degree program.",
    course_img: "", 
    org_img: "",
    org: "", 
    rating: "", 
    enrolled: "", 
    categories: [], 
    status: [],
    skills: "",
    type: "",
    url: ""
  },
  { id: 2, 
    intro: false,
    category: "All",
    product: "degree",
    title: "Bachelor of Science in General Business", 
    subTitle: "",
    course_img: businessCard, 
    org_img: [unt],
    org: ["University of North Texas"], 
    rating: "", 
    enrolled: "1.1m students", 
    categories: ["Degree", "15+ hours of study/wk per course"], 
    status: [],
    skills: "Analysis, Business Analysis, Chart, Computational Logic, Computer Science",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 3, 
    intro: false,
    category: "All",
    product: "degree",
    title: "Master of Business Administration (iMBA)", 
    subTitle: "",
    course_img: adminCard, 
    org_img: [uOfIllinois],
    org: ["University of Illinois at Urbana-Champaign"], 
    rating: "", 
    enrolled: "1.1m students", 
    categories: ["Degree", "2-3 years"], 
    status: [],
    skills: "Accounting, Algorithms, Applied Machine Learning, Artificial Neural Network",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
  { id: 4, 
    intro: false,
    category: "All",
    product: "degree",
    title: "Master of Applied Data Science", 
    subTitle: "",
    course_img: dataScienceCard, 
    org_img: [michigan],
    org: ["University of Michigan"], 
    rating: "", 
    enrolled: "1.1m students", 
    categories: ["Degree", "1-3 years"], 
    status: [],
    skills: "Algorithms, BlockChain, Computer Networking, Computer Security",
    type: "",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science"
  },
]

export { tabs, skill, course, specialization, degree };
